services:
  site:
    build: .
    working_dir: /srv/jekyll
    command: bash -lc "bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    environment:
      JEKYLL_ENV: development

volumes:
  bundle:
